#
#   - Ganglia::Gmetric::PP -
#   This spec file was automatically generated by cpan2rpm [ver: 2.027]
#   The following arguments were used:
#       Ganglia-Gmetric-PP-0.95.tar.gz
#   For more information on cpan2rpm please visit: http://perl.arix.com/
#

%define pkgname Ganglia-Gmetric-PP
%define NVR %{pkgname}-%{version}-%{release}
%define maketest 1

name:      perl-Ganglia-Gmetric-PP
summary:   Ganglia-Gmetric-PP - Pure Perl emitter of Ganglia monitoring packets
version:   0.95
release:   1
vendor:    Adam Thomason <athomason@cpan.org>
packager:  Arix International <cpan2rpm@arix.com>
license:   Artistic
group:     Applications/CPAN
url:       http://www.cpan.org
buildroot: %{_tmppath}/%{name}-%{version}-%(id -u -n)
buildarch: noarch
prefix:    %(echo %{_prefix})
source:    Ganglia-Gmetric-PP-0.95.tar.gz

%description
This module constructs Ganglia packets in the manner of the gmetric program and
sends them via UDP to a gmond. Though written in pure Perl with no non-core
dependencies, it tries to be quite fast.

#
# This package was generated automatically with the cpan2rpm
# utility.  To get this software or for more information
# please visit: http://perl.arix.com/
#

%prep
%setup -q -n %{pkgname}-%{version} 
chmod -R u+w %{_builddir}/%{pkgname}-%{version}

%build
grep -rsl '^#!.*perl' . |
grep -v '.bak$' |xargs --no-run-if-empty \
%__perl -MExtUtils::MakeMaker -e 'MY->fixin(@ARGV)'
CFLAGS="$RPM_OPT_FLAGS"
%{__perl} Makefile.PL `%{__perl} -MExtUtils::MakeMaker -e ' print qq|PREFIX=%{buildroot}%{_prefix}| if \$ExtUtils::MakeMaker::VERSION =~ /5\.9[1-6]|6\.0[0-5]/ '`
%{__make} 
%if %maketest
%{__make} test
%endif

%install
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

%{makeinstall} `%{__perl} -MExtUtils::MakeMaker -e ' print \$ExtUtils::MakeMaker::VERSION <= 6.05 ? qq|PREFIX=%{buildroot}%{_prefix}| : qq|DESTDIR=%{buildroot}| '`

%clean
[ "%{buildroot}" != "/" ] && rm -rf %{buildroot}

%files

Changes
Makefile.PL
MANIFEST
MANIFEST.SKIP
README
Ganglia-Gmetric-PP.spec
lib/Ganglia/Gmetric/PP.pm
%attr(775,-,-) bin/gmetric-aggregator.pl
%attr(775,-,-) bin/gmetric.pl
t/Ganglia-Gmetric-PP.t
t/gmetric-aggregator.t
t/gmetric.t
t/gen-test-data.pl
META.yml                                 Module meta-data (added by MakeMaker)

%defattr(-,root,root)

%changelog
* Thu Sep 10 2009 athomason@athomason-many
- Initial build.
